import base64
import struct

import pytest
from PIL import Image, PngImagePlugin

from snitch import core

# A 97x61 interlaced PNG generated by ImageMagick. Keeping the fixture inline avoids making CI
# depend on ImageMagick merely to construct a standards-compliant Adam7 image.
INTERLACED_PNG = base64.b64decode(
    "iVBORw0KGgoAAAANSUhEUgAAAGEAAAA9AQMAAAHwg6X6AAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1"
    "MAAA6mAAADqYAAAXcJy6UTwAAAAGUExURRlatP///2GzwikAAAABYktHRAH/Ai3eAAAAB3RJTUUH6ggZ"
    "CwAChDFPXQAAABFJREFUKM9jYBgFo2AUDAoAAAONAAHbg+t5AAAAEXRFWHRBdXRob3IASm9z6SDBbmdlbPpz"
    "O48AAAAUdEVYdENvbW1lbnQAcHJpdmF0ZSBub3RllEpQCQAAAABJRU5ErkJggg=="
)


def png_chunk_names(path):
    data = path.read_bytes()
    names = []
    offset = 8
    while offset < len(data):
        length = struct.unpack(">I", data[offset:offset + 4])[0]
        names.append(data[offset + 4:offset + 8])
        offset += length + 12
    return names


def test_strip_jpeg_keeps_jfif_orientation_and_icc_but_removes_private_exif(tmp_path):
    source = tmp_path / "source.jpg"
    output = tmp_path / "clean.jpg"
    exif = Image.Exif()
    exif[274] = 6
    exif[315] = "Private Artist"
    Image.new("RGB", (31, 19), "purple").save(
        source, "JPEG", exif=exif, icc_profile=b"audit fake profile", comment=b"private comment"
    )

    removed = core.strip_jpeg(source, output)

    clean = output.read_bytes()
    assert removed > 0
    assert b"JFIF\x00" in clean
    assert b"ICC_PROFILE\x00" in clean
    assert b"Private Artist" not in clean
    assert b"private comment" not in clean
    with Image.open(output) as image:
        assert image.getexif()[274] == 6
        assert 315 not in image.getexif()
        assert image.info["icc_profile"] == b"audit fake profile"
    assert core.pixels_identical(source, output)


def test_strip_cmyk_jpeg_keeps_adobe_colour_transform(tmp_path):
    source = tmp_path / "source.jpg"
    output = tmp_path / "clean.jpg"
    Image.new("CMYK", (31, 19), (12, 34, 56, 7)).save(source, "JPEG")

    core.strip_jpeg(source, output)

    assert b"Adobe" in output.read_bytes()
    assert core.pixels_identical(source, output)


@pytest.mark.parametrize("kind", ["rgb", "rgba", "palette", "interlaced"])
def test_strip_png_variants_preserve_pixels_and_remove_text(tmp_path, kind):
    source = tmp_path / f"{kind}.png"
    output = tmp_path / f"{kind}-clean.png"
    info = PngImagePlugin.PngInfo()
    info.add_text("Comment", "private note")
    if kind == "rgb":
        Image.new("RGB", (31, 19), "teal").save(source, pnginfo=info)
    elif kind == "rgba":
        Image.new("RGBA", (31, 19), (10, 20, 30, 40)).save(source, pnginfo=info)
    elif kind == "palette":
        image = Image.new("P", (31, 19))
        image.putpalette([channel for value in range(256) for channel in (value, value, value)])
        image.info["transparency"] = 0
        image.save(source, pnginfo=info)
    else:
        source.write_bytes(INTERLACED_PNG)

    core.strip_png(source, output)

    assert core.pixels_identical(source, output)
    assert b"tEXt" not in png_chunk_names(output)
    with Image.open(output) as image:
        if kind == "rgba":
            assert image.mode == "RGBA"
        elif kind == "palette":
            assert image.mode == "P"
            assert image.info["transparency"] == 0
        elif kind == "interlaced":
            assert image.info["interlace"] == 1


def test_strip_png_preserves_orientation_and_icc(tmp_path):
    source = tmp_path / "source.png"
    output = tmp_path / "clean.png"
    exif = Image.Exif()
    exif[274] = 8
    exif[315] = "Private Artist"
    Image.new("RGB", (31, 19), "navy").save(
        source, exif=exif, icc_profile=b"audit fake profile"
    )

    core.strip_png(source, output)

    with Image.open(output) as image:
        assert image.getexif()[274] == 8
        assert 315 not in image.getexif()
        assert image.info["icc_profile"] == b"audit fake profile"
    assert core.pixels_identical(source, output)


def test_strip_png_preserves_animation(tmp_path):
    source = tmp_path / "animated.png"
    output = tmp_path / "animated-clean.png"
    first = Image.new("RGBA", (31, 19), "red")
    second = Image.new("RGBA", (31, 19), "blue")
    first.save(source, save_all=True, append_images=[second], duration=[100, 200], loop=0)

    core.strip_png(source, output)

    with Image.open(output) as image:
        assert image.n_frames == 2
    assert core.pixels_identical(source, output)


@pytest.mark.parametrize("mutation", ["truncate", "crc"])
def test_strip_png_rejects_corruption_without_output(tmp_path, mutation):
    source = tmp_path / "source.png"
    output = tmp_path / "clean.png"
    Image.new("RGB", (31, 19), "red").save(source)
    data = bytearray(source.read_bytes())
    if mutation == "truncate":
        del data[-5:]
    else:
        data[29] ^= 0x01
    source.write_bytes(data)

    with pytest.raises(ValueError):
        core.strip_png(source, output)

    assert not output.exists()


@pytest.mark.parametrize("data", [b"", b"\xff\xd8", b"\xff\xd8\xff\xe1\x00\x01"])
def test_strip_jpeg_rejects_malformed_inputs_without_output(tmp_path, data):
    source = tmp_path / "source.jpg"
    output = tmp_path / "clean.jpg"
    source.write_bytes(data)

    with pytest.raises(ValueError):
        core.strip_jpeg(source, output)

    assert not output.exists()
